[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000

[browser]
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
